### PR TITLE
Update lists of empty element, and special attributes

### PR DESCRIPTION
**Pull request by dairiki**
This pull request updates the lists of _empty elements_, _boolean attributes_ and _composed (multi-valued) attributes_ in `webhelpers2.html.builder.HTML` to include all of the appropriate values I could glean from the current draft HTML 5.1 specs.

This change might result in some breakage of deployed code, but I think it is worth it, for the sake of consistency.

E.g., I just (naively) wrote:

```
tag = HTML.script(src='foo', defer='', async='')
```

This, with WebHelpers2==2.0, produced, to my surprise

```
<script src="foo" async=''></script>
```

Note that the `defer` attribute was elided as a boolean attribute with a falsy value, while the `async` attribute was not, since currently webhelpers does not think it is a boolean attribute.  After this PR, both the `defer` and  `async` attributes will be elided. 

Anyhow, here it is...

### CODE REVIEW

**Comment by mikeorr** [comment]
It looks good at first pass. I want to consult one user who's currently using WebHelpers2 integrated with Javascript/HTML5; he's away until July 12th.

What does the script do if the URL or target tags or items aren't found? It should raise an exception to indicate the result is invalid, rather than silently giving a wrong answer.

The HTML package is primarily for HTML5, and secondarily for HTML4 or arbitrary XML tags (arbitrary attributes). I doubt many users have arbitrary XML tags with conflicting attributes, and I've tried to encourage people to pin their application to a certain version of WebHelpers2 to avoid the problems that came up in WebHelpers.

In the meantime, the recommended way to deal with conflicting attribute types if the default is unsuitable with your application, is to modify 'void_tags', 'boolean_attrs', and 'compose_attrs' globally at application launch. Is that clear enough in the docs?

**Comment by dairiki** [comment]
I didn't really intend for the script to be bomb-proof. It's really just an enhanced "grep" I used to try to ensure that I had found all the appropriate elements and attributes in my manual scan of the spec.  (There seems to be no official machine-parseable grammar/schema/dtd for HTML5 — at least, I could not find one.)  The script is not intended for general use (and feel free to omit it from the PR) so I didn't really see the need for too many checks or guaranteed correctness.  (In fact, since there in a fair amount of ad-hocnicity involved, there's no guarantee that it's correct, even now — especially with regard to having found the complete set of *composed attributes*.)  That said, I think most modes of future failure will result in a (possibly cryptic) exception  (404s, missing tables, changes in table column headings)  or an empty list of attributes/elements (changes in an expected phrase.like `"Boolean attribute"`.)  In either case, it should be fairly obvious to a human interpreter of the results that something is wrong.

I think the docs are clear enough as is.  But thank you for the reminder — I've just updated them to reflect the changes in this PR.  ;-)

**Comment by mikeorr** [comment]
Put the script in the 'unfinished' directory with a comment at the top about how reliable you think it is. That way it will be accessible as a reference but we don't have to think about 'finalizing' it right now. I had intended to keep the lists updated manually, and if W3C doesn't provide an official machine-readable format it's probably better that way, but the script will still be available to use as a tool later.

**Comment by dairiki** [comment]
Okay, I've converted the scraping script to a real `py.test` test script (in `webhelpers2/tests/check_html_spec.py`) which checks that the values in `HTML.void_tags`, `HTML .boolean_attrs`, and `HTML.compose_attrs` agree with the scraped values.  I’ve also added a few more checks in a attempt to ensure that the scrape results look sane.

Since the module name does not start with `test_`, `py.test` won't collect it by default.  You have to explicitly name the script (or change the setting of `python_files` in your `pytest.ini`) to run it.  I did however, add a `spec` environment to the `tox` configuration which does run the test.

**Comment by dairiki** [comment]
I've just updated this PR to track changes in the HTML5.1 draft spec.

Among the changes: the microdata attributes (including `itemprop`, `itemtype`, `itemref`, and `itemscope`) have been removed from the HTML5.1 draft specification, however they do live on in an older [HTML extension](https://www.w3.org/TR/microdata/).  For now I've removed them from ``HTML.boolean_attrs` and `HTML.compose_attrs`, though I'm not completely sure that is the best way to handle them.

**Comment by mikeorr** [comment]
Merged.

My principle for void/boolean/composed attributes is to include anything a large cross-section of users would want. We can use comments to specify which authority they came from, as you've already done. Do HTML users have to "include" extensions somehow, or just use the attributes. We could get sophisticated with a method to insert/delete attributes from different authorities into the lists;users would call this during application initialization. Or we can just keep the current practice of having them edit the lists if they don't like the defaults.

**Comment by dairiki** [comment]
> My principle for void/boolean/composed attributes is to include anything a large cross-section of users would want.

Makes sense.

As a data point, I do currently use microdata (however not via WebHelpers), so perhaps those attributes should be included.  (I.e. revert a0cb6a8.)

I've not found a machine parseable description of the microdata attributes (though I doubt the specs will be changing much — the last update was 2013) so it would be tricky to update the [test script](https://github.com/mikeorr/WebHelpers2/blob/master/webhelpers2/tests/check_html_spec.py) to check the actual spec.

----

I'm not sure what other extensions may be worth considering...  There are the WAI-ARIA attributes (about which I am no expert,) but I'm not sure any of those require special treatment within the scope of WebHelpers2.

**Pull request merged**
